sudo: false

language: rust
rust: nightly

addons:
  apt:
    packages:
      - libpam0g-dev
  
git:
  depth: 1

before_script:
  - cargo install rustfmt
  - cargo install clippy

script:
  - cargo build --verbose
  - cargo clippy
  - ~/.cargo/bin/rustfmt --write-mode checkstyle src/pam_setquota.rs > /dev/null
